#
# Makefile for the touchscreen drivers.
#

obj-$(CONFIG_TOUCHPANEL_OPPO) += util_interface/
obj-$(CONFIG_TOUCHPANEL_OPPO) += touch.o
obj-$(CONFIG_TOUCHPANEL_OPPO) += touchpanel_common_driver.o touchpanel_prevention.o
obj-$(CONFIG_TOUCHPANEL_NOVA) += Novatek/
